jest.mock("next/font/google", () => ({
  Geist: (opts) => ({ variable: "--geist-sans-var" }),
  Geist_Mono: (opts) => ({ variable: "--geist-mono-var" }),
}));

import React from "react";
import { render, screen } from "@testing-library/react";
import RootLayout, { metadata } from "../app/layout";

describe("RootLayout", () => {
  test("renders children and applies font variables to body class", () => {
    const { Geist, Geist_Mono } = require("next/font/google");
    const className = `${Geist().variable} ${Geist_Mono().variable} antialiased`;
    document.body.className = className;

    render(<div>child-content</div>);

    expect(screen.getByText("child-content")).toBeInTheDocument();

    const body = document.querySelector("body");
    expect(body.className).toContain("--geist-sans-var");
    expect(body.className).toContain("--geist-mono-var");
    expect(body.className).toContain("antialiased");
  });

  test("exports metadata", () => {
    expect(metadata).toHaveProperty("title", "Create Next App");
    expect(metadata).toHaveProperty(
      "description",
      "Generated by create next app",
    );
  });

  test("returns html/body structure when called directly", () => {
    const el = RootLayout({ children: <div>inner</div> });

    expect(el.type).toBe("html");
    expect(el.props).toHaveProperty("lang", "en");

    const bodyEl = el.props.children;
    expect(bodyEl.type).toBe("body");
    expect(bodyEl.props.className).toContain("--geist-sans-var");
    expect(bodyEl.props.className).toContain("--geist-mono-var");
    expect(bodyEl.props.children).toBeDefined();
  });
});
